# Generated by Django 4.0.6 on 2022-07-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('level', models.CharField(choices=[('1', '1 basico'), ('2', '2 basico'), ('3', '3 basico'), ('4', '4 basico')], default='1', max_length=1)),
                ('section', models.CharField(choices=[('A', 'Sección A'), ('B', 'Sección B'), ('C', 'Sección C'), ('D', 'Sección D')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_date', models.DateField(verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fullname', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='myre.grade')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grade', to='myre.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='School', to='myre.project')),
                ('id_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='myre.school')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='id_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myre.school'),
        ),
        migrations.AddConstraint(
            model_name='student_grade',
            constraint=models.UniqueConstraint(fields=('id_student', 'id_grade'), name='unique student on a grade'),
        ),
        migrations.AddConstraint(
            model_name='project_data',
            constraint=models.UniqueConstraint(fields=('id_project', 'id_school'), name='unique school on a proyect'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('year', 'level', 'section', 'id_school'), name='unique grade on a year'),
        ),
    ]
