# Generated by Django 4.0.6 on 2022-07-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myre', '0002_student_grade_unique student on a year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student_grade',
            name='unique student on a year',
        ),
    ]
